;;; wallabag-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from wallabag.el

(autoload 'wallabag-find "wallabag" "\
Find the entry from list using ivy or consult." t)
(autoload 'wallabag "wallabag" "\
Enter the *wallbag-search* buffer." t)
(autoload 'wallabag-toggle-sidebar "wallabag" "\
Toggle visibility of project sidebar window." t)
(autoload 'wallabag-goto-sidebar "wallabag" "\
Create or goto sidebar window." t)
(register-definition-prefixes "wallabag" '("wallabag-"))


;;; Generated autoloads from wallabag-db.el

(register-definition-prefixes "wallabag-db" '("wallabag-db"))


;;; Generated autoloads from wallabag-org.el

(autoload 'wallabag-org-link-view "wallabag-org" "\
Follow wallabag org links by ID.

(fn ID _)")
(register-definition-prefixes "wallabag-org" '("wallabag-org-"))


;;; Generated autoloads from wallabag-util.el

(register-definition-prefixes "wallabag-util" '("wallabag-"))

;;; End of scraped data

(provide 'wallabag-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wallabag-autoloads.el ends here
