;;; markdown-table-wrap-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from markdown-table-wrap.el

(register-definition-prefixes "markdown-table-wrap" '("markdown-table-wrap"))


;;; Generated autoloads from markdown-table-wrap-pretty.el

(autoload 'markdown-table-wrap-pretty-mode "markdown-table-wrap-pretty"
"Toggle display-only pretty rendering of pipe tables in this buffer.

When on, tables can be toggled between a pretty view and the canonical
raw pipe text with `markdown-table-wrap-pretty-toggle'.  Resize
re-renders pretty tables losslessly when
`markdown-table-wrap-pretty-auto-rewrap-on-resize' is on.  Tables
start raw unless the major mode is in
`markdown-table-wrap-pretty-default-on-major-modes'.  Editing a pretty
table auto-reveals the raw source via `modification-hooks' (the
`org-latex-preview' pattern; not `read-only', which would break undo).

This is a minor mode.  If called interactively, toggle the
`Markdown-Table-Wrap-Pretty mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `markdown-table-wrap-pretty-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'markdown-table-wrap-pretty-toggle "markdown-table-wrap-pretty"
"Toggle the pretty rendering of the pipe table at point, or all tables.
Mirrors `org-latex-preview'.  ARG selects the force behavior: a single
prefix arg forces pretty on every table, a double prefix arg forces
raw; otherwise the location rules below decide:
  - Point on a table  -> toggle that table.
  - Point off-table    -> toggle all tables in the buffer (if any are
    pretty, make all raw; otherwise make all pretty).
  - Active region      -> toggle tables overlapping the region.

(fn &optional ARG)" t)
(autoload 'markdown-table-wrap-pretty-buffer "markdown-table-wrap-pretty"
"Force pretty rendering on all tables in the current buffer." t)
(autoload 'markdown-table-wrap-pretty-region "markdown-table-wrap-pretty"
"Force pretty rendering on all tables in BEG..END.

(fn BEG END)" t)
(register-definition-prefixes "markdown-table-wrap-pretty" '("markdown-table-wrap-pretty-"))

;;; End of scraped data

(provide 'markdown-table-wrap-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; markdown-table-wrap-autoloads.el ends here
