;;; msgpack-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from msgpack.el

(autoload 'msgpack-read "msgpack"
"Parse and return the MessagePack object following point.
Advances point just past MessagePack object.

ARRAY-TYPE, MAP-TYPE, KEY-TYPE, BIN-TYPE, NULL-VALUE, and FALSE-VALUE override
the corresponding dynamic defaults for this read and all nested values.  For
backwards compatibility, FALSE-VALUE defaults to nil.

(fn &key (ARRAY-TYPE msgpack-array-type) (MAP-TYPE msgpack-map-type) (KEY-TYPE msgpack-key-type) (BIN-TYPE msgpack-bin-type) (NULL-VALUE msgpack-null) (FALSE-VALUE nil))")
(autoload 'msgpack-decode "msgpack"
"Read the first MessagePack object in unibyte STRING and return it.
ARGS are keyword arguments forwarded to `msgpack-read'.

(fn STRING &rest ARGS)")
(register-definition-prefixes "msgpack" '("msgpack-"))

;;; End of scraped data

(provide 'msgpack-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; msgpack-autoloads.el ends here
