;;; pilish-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pilish.el

(autoload 'pilish "pilish"
"Start or switch to pi coding agent session in current project.
With prefix arg, prompt for SESSION name to allow multiple sessions.
If already in a pi buffer and no SESSION specified, ensures this session
is visible. When both chat and input are already shown in the current
frame, keeps layout unchanged and focuses the input window.

(fn &optional SESSION)" t)
(autoload 'pilish-open-session-file "pilish"
"Open pi JSONL SESSION-FILE as a live session.
This uses the normal chat/input UI and switches pi to SESSION-FILE; it is not a
static viewer.  The session header must record a non-empty absolute cwd that
names an existing directory.  Interactively, prompt for an existing file.  In
Dired, default to the regular file at point; otherwise, default to the current
visited local regular readable .jsonl file when there is one.

(fn SESSION-FILE)" t)
(autoload 'pilish-toggle "pilish"
"Toggle pi coding agent window visibility for the current project.
If pi windows are visible in the current frame, hide them.
If hidden there but a session exists, show them.
If no session exists, signal an error." t)
(register-definition-prefixes "pilish" '("pilish-"))


;;; Generated autoloads from pilish-browse.el

(autoload 'pilish-session-browser "pilish-browse"
"Open the session browser for the current project.
A new browser starts from `pilish-session-browser-default-scope',
`pilish-session-browser-default-view', and
`pilish-session-browser-default-named-only'; an existing (even
hidden) browser buffer is reused with its current state.  Re-running
the browser major mode re-initializes from the current defaults." t)
(autoload 'pilish-tree-browser "pilish-browse"
"Open the tree browser for the current session.
Guard first: the tree browser reads the linked chat's session file
from disk, so without a live chat session there is nothing to browse
— signal `user-error' \"No pi session to browse\" BEFORE creating any
browser buffer (a buffer with no link would only render the link
error forever).  A new browser starts from
`pilish-tree-browser-default-filter'; an existing (even hidden)
browser buffer is reused with its current state.  Re-running the
browser major mode re-initializes from the current defaults." t)
(register-definition-prefixes "pilish-browse" '("pilish-"))


;;; Generated autoloads from pilish-core.el

(register-definition-prefixes "pilish-core" '("pilish-"))


;;; Generated autoloads from pilish-evil.el

(autoload 'pilish-evil-setup "pilish-evil"
"Set up Evil integration for Pilish.
Set initial buffer states, install keybindings, and apply the user
options `pilish-evil-chat-state',
`pilish-evil-input-state',
`pilish-evil-browse-state',
`pilish-evil-copy-raw-markdown', and
`pilish-evil-disable-snipe'.  Safe to call more than once." t)
(register-definition-prefixes "pilish-evil" '("pilish-"))


;;; Generated autoloads from pilish-grammars.el

(autoload 'pilish-install-grammars "pilish-grammars"
"Show grammar status and install missing tree-sitter grammars.
Displays which grammars are installed and which are missing,
then offers to install the missing ones." t)
(register-definition-prefixes "pilish-grammars" '("pilish-"))


;;; Generated autoloads from pilish-input.el

(autoload 'pilish-attach-image "pilish-input"
"Attach one materialized image to the current prompt draft.
With prefix argument CLEAR, remove the attached image instead.  A new image
replaces the previous draft image.

(fn &optional CLEAR)" t)
(register-definition-prefixes "pilish-input" '("pilish-"))


;;; Generated autoloads from pilish-jsonl.el

(register-definition-prefixes "pilish-jsonl" '("pilish-"))


;;; Generated autoloads from pilish-menu.el

(autoload 'pilish-new-session "pilish-menu"
"Start a new pi session (reset)." t)
(autoload 'pilish-reload "pilish-menu"
"Reload the current session by restarting the pi process.
Useful for reloading extensions, skills, prompts, and themes after
editing them, or when the pi process has died or become unresponsive.
Starts a fresh process, switches it back to the cached session file, then
replaces the old process, refreshes state and commands, and rebuilds the chat
buffer from session history." t)
(register-definition-prefixes "pilish-menu" '("pilish-"))


;;; Generated autoloads from pilish-render.el

(register-definition-prefixes "pilish-render" '("pilish-"))


;;; Generated autoloads from pilish-table.el

(register-definition-prefixes "pilish-table" '("pilish-"))


;;; Generated autoloads from pilish-ui.el

(register-definition-prefixes "pilish-ui" '("pilish-"))

;;; End of scraped data

(provide 'pilish-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pilish-autoloads.el ends here
